name: news_tdd
description: "A new Flutter project."
    
    
publish_to: 'none'     

    
    
    
    
    
    
    
    
    
    
    
    
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-174.2.beta <4.0.0'

    
    
    
    
    
    
dependencies:
  flutter:
    sdk: flutter


      
      
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

    
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  build_web_compilers: any

      
      
      
      
      
  flutter_lints: ^3.0.0

    
    

    
flutter:

      
      
      
  uses-material-design: true

      
      
      
      

      
      

      
      

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
